from pydantic import BaseModel, Field
from typing import List

class ChatRequest(BaseModel):
    thread_id: str = Field(..., description="Unique identifier for the chat session")
    message: str = Field(..., description="The user's input message")

class ChatResponse(BaseModel):
    messages: List[str] = Field(default_factory=list, description="List of messages generated by the AI in this turn")
